# Form implementation generated from reading ui file 'ui/jog_control.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(717, 722)
        MainWindow.setMinimumSize(QtCore.QSize(689, 660))
        MainWindow.setMaximumSize(QtCore.QSize(725, 16777215))
        MainWindow.setStyleSheet("\n"
"/* === BASE === */\n"
"QMainWindow {\n"
"    background-color: #F9F9F9;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;\n"
"    color: #1A1A18;\n"
"}\n"
"\n"
"/* === TABS === */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #E2E2DC;\n"
"    background: #F9F9F9;\n"
"    border-radius: 0px 6px 6px 6px;\n"
"    top: -1px;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: left;\n"
"}\n"
"QTabBar::tab {\n"
"    background: transparent;\n"
"    color: #72716D;\n"
"    padding: 7px 18px;\n"
"    border: 1px solid transparent;\n"
"    border-bottom: none;\n"
"    border-radius: 6px 6px 0 0;\n"
"    font-size: 9pt;\n"
"    min-width: 80px;\n"
"    margin-right: 2px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #FFFFFF;\n"
"    border-color: #E2E2DC;\n"
"    border-bottom-color: #FFFFFF;\n"
"    color: #1A1A18;\n"
"    font-weight: 600;\n"
"}\n"
"QTabBar::tab:hover:!selected {\n"
"    background: #F4F4F0;\n"
"    color: #1A1A18;\n"
"}\n"
"\n"
"/* === LABELS === */\n"
"QLabel {\n"
"    color: #1A1A18;\n"
"    font-size: 10pt;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* === LINE EDIT === */\n"
"QLineEdit {\n"
"    height: 26px;\n"
"    padding: 0 8px;\n"
"    border: 1px solid #CBCAC5;\n"
"    border-radius: 5px;\n"
"    background: #FFFFFF;\n"
"    color: #1A1A18;\n"
"    font-size: 10pt;\n"
"    selection-background-color: #E6F1FB;\n"
"    selection-color: #185FA5;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #185FA5;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background: #F4F4F0;\n"
"    color: #A09F9B;\n"
"}\n"
"\n"
"/* === SPINBOX === */\n"
"QSpinBox, QDoubleSpinBox {\n"
"    height: 26px;\n"
"    padding: 0 6px;\n"
"    border: 1px solid #CBCAC5;\n"
"    border-radius: 5px;\n"
"    background: #FFFFFF;\n"
"    color: #1A1A18;\n"
"    font-size: 10pt;\n"
"    selection-background-color: #E6F1FB;\n"
"}\n"
"QSpinBox:focus, QDoubleSpinBox:focus { border-color: #185FA5; }\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 18px;\n"
"    border-left: 1px solid #CBCAC5;\n"
"    border-bottom: 1px solid #CBCAC5;\n"
"    border-radius: 0 5px 0 0;\n"
"    background: #F4F4F0;\n"
"}\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    width: 18px;\n"
"    border-left: 1px solid #CBCAC5;\n"
"    border-radius: 0 0 5px 0;\n"
"    background: #F4F4F0;\n"
"}\n"
"QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover,\n"
"QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover {\n"
"    background: #E2E2DC;\n"
"}\n"
"\n"
"/* === COMBOBOX === */\n"
"QComboBox {\n"
"    height: 26px;\n"
"    padding: 0 8px;\n"
"    border: 1px solid #CBCAC5;\n"
"    border-radius: 5px;\n"
"    background: #FFFFFF;\n"
"    color: #1A1A18;\n"
"    font-size: 10pt;\n"
"}\n"
"QComboBox:focus { border-color: #185FA5; }\n"
"QComboBox:disabled { background: #F4F4F0; color: #A09F9B; }\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 22px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background: #FFFFFF;\n"
"    border: 1px solid #E2E2DC;\n"
"    border-radius: 5px;\n"
"    selection-background-color: #E6F1FB;\n"
"    selection-color: #185FA5;\n"
"    padding: 2px;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* === BOTONES — BASE === */\n"
"QPushButton {\n"
"    height: 30px;\n"
"    padding: 0 14px;\n"
"    border: 1px solid #CBCAC5;\n"
"    border-radius: 5px;\n"
"    background: #FFFFFF;\n"
"    color: #1A1A18;\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"}\n"
"QPushButton:hover { background: #F4F4F0; border-color: #AAAAAA; }\n"
"QPushButton:pressed { background: #E9E8E3; }\n"
"QPushButton:disabled { color: #A09F9B; border-color: #E2E2DC; background: #F4F4F0; }\n"
"\n"
"/* === BOTÓN PRIMARIO === */\n"
"QPushButton#run_Button {\n"
"    background: #185FA5;\n"
"    border-color: #185FA5;\n"
"    color: #E6F1FB;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton#run_Button:hover { background: #0C447C; border-color: #0C447C; }\n"
"QPushButton#run_Button:pressed { background: #0A3869; }\n"
"QPushButton#run_Button:disabled { background: #A8C8E8; border-color: #A8C8E8; color: #DDEEFF; }\n"
"\n"
"QPushButton#SaveConfig_Button,\n"
"QPushButton#SavePoints_Button,\n"
"QPushButton#AddPoint_Button,\n"
"QPushButton#GoToPoint_Button {\n"
"    background: #185FA5;\n"
"    border-color: #185FA5;\n"
"    color: #E6F1FB;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton#SaveConfig_Button:hover,\n"
"QPushButton#SavePoints_Button:hover,\n"
"QPushButton#AddPoint_Button:hover,\n"
"QPushButton#GoToPoint_Button:hover { background: #0C447C; border-color: #0C447C; }\n"
"\n"
"/* === BOTÓN DANGER === */\n"
"QPushButton#stop_Button {\n"
"    background: #FCEBEB;\n"
"    border-color: #E24B4A;\n"
"    color: #A32D2D;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton#stop_Button:hover { background: #F9D5D5; }\n"
"QPushButton#stop_Button:pressed { background: #F0BFBF; }\n"
"QPushButton#stop_Button:disabled { background: #F4F4F0; border-color: #E2E2DC; color: #A09F9B; }\n"
"\n"
"QPushButton#DeleteRecipe_Button,\n"
"QPushButton#DeletePoint_Button,\n"
"QPushButton#ReleaseServos_Button {\n"
"    background: #FCEBEB;\n"
"    border-color: #E24B4A;\n"
"    color: #A32D2D;\n"
"}\n"
"QPushButton#DeleteRecipe_Button:hover,\n"
"QPushButton#DeletePoint_Button:hover,\n"
"QPushButton#ReleaseServos_Button:hover { background: #F9D5D5; }\n"
"\n"
"/* === BOTÓN SUCCESS === */\n"
"QPushButton#TeachPoint,\n"
"QPushButton#LockServos_Button,\n"
"QPushButton#AddRecipe_Button {\n"
"    background: #E1F5EE;\n"
"    border-color: #1D9E75;\n"
"    color: #0F6E56;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton#TeachPoint:hover,\n"
"QPushButton#LockServos_Button:hover,\n"
"QPushButton#AddRecipe_Button:hover { background: #C8EEE1; }\n"
"\n"
"/* === JOG BUTTONS === */\n"
"QPushButton[objectName*=\"jog_plus_Button\"],\n"
"QPushButton[objectName*=\"jog_minus_Button\"] {\n"
"    font-size: 14pt;\n"
"    font-weight: 700;\n"
"    border: 1px solid #CBCAC5;\n"
"    border-radius: 5px;\n"
"    background: #F4F4F0;\n"
"    color: #1A1A18;\n"
"    min-height: 52px;\n"
"}\n"
"QPushButton[objectName*=\"jog_plus_Button\"]:hover,\n"
"QPushButton[objectName*=\"jog_minus_Button\"]:hover {\n"
"    background: #EAEAE5;\n"
"    border-color: #999896;\n"
"}\n"
"QPushButton[objectName*=\"jog_plus_Button\"]:pressed { background: #E6F1FB; color: #185FA5; }\n"
"QPushButton[objectName*=\"jog_minus_Button\"]:pressed { background: #FCEBEB; color: #A32D2D; }\n"
"QPushButton[objectName*=\"jog_plus_Button\"]:disabled,\n"
"QPushButton[objectName*=\"jog_minus_Button\"]:disabled {\n"
"    background: #F4F4F0;\n"
"    color: #C0BFBB;\n"
"    border-color: #E2E2DC;\n"
"}\n"
"\n"
"/* === TABLAS === */\n"
"QTableWidget {\n"
"    background: #FFFFFF;\n"
"    border: 1px solid #E2E2DC;\n"
"    border-radius: 5px;\n"
"    gridline-color: #E2E2DC;\n"
"    alternate-background-color: #F9F9F7;\n"
"    font-size: 10pt;\n"
"    color: #1A1A18;\n"
"    selection-background-color: #E6F1FB;\n"
"    selection-color: #0C447C;\n"
"}\n"
"QTableWidget::item { padding: 5px 8px; }\n"
"QTableWidget::item:selected {\n"
"    background: #E6F1FB;\n"
"    color: #0C447C;\n"
"}\n"
"QHeaderView::section {\n"
"    background: #F4F4F0;\n"
"    color: #72716D;\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"    padding: 6px 8px;\n"
"    border: none;\n"
"    border-right: 1px solid #E2E2DC;\n"
"    border-bottom: 1px solid #CBCAC5;\n"
"}\n"
"QHeaderView::section:last { border-right: none; }\n"
"QTableCornerButton::section { background: #F4F4F0; border: none; }\n"
"\n"
"/* === LISTAS === */\n"
"QListWidget {\n"
"    background: #FFFFFF;\n"
"    border: 1px solid #E2E2DC;\n"
"    border-radius: 5px;\n"
"    font-size: 10pt;\n"
"    color: #1A1A18;\n"
"    outline: none;\n"
"}\n"
"QListWidget::item {\n"
"    padding: 7px 12px;\n"
"    border-bottom: 1px solid #F0F0EB;\n"
"}\n"
"QListWidget::item:hover { background: #F4F4F0; }\n"
"QListWidget::item:selected {\n"
"    background: #E6F1FB;\n"
"    color: #185FA5;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* === FRAMES === */\n"
"QFrame {\n"
"    background: #FFFFFF;\n"
"    border: 1px solid #E2E2DC;\n"
"    border-radius: 6px;\n"
"}\n"
"QFrame[frameShape=\"0\"] {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* === SLIDERS === */\n"
"QSlider::groove:horizontal {\n"
"    height: 4px;\n"
"    background: #E2E2DC;\n"
"    border-radius: 2px;\n"
"    margin: 0 0;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #185FA5;\n"
"    border: none;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:horizontal:hover { background: #0C447C; }\n"
"QSlider::sub-page:horizontal {\n"
"    background: #185FA5;\n"
"    border-radius: 2px;\n"
"}\n"
"QSlider::groove:horizontal:disabled { background: #E2E2DC; }\n"
"QSlider::handle:horizontal:disabled { background: #CBCAC5; }\n"
"\n"
"/* === RADIO BUTTONS === */\n"
"QRadioButton {\n"
"    color: #1A1A18;\n"
"    font-size: 10pt;\n"
"    spacing: 6px;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border: 1px solid #CBCAC5;\n"
"    border-radius: 7px;\n"
"    background: #FFFFFF;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: #185FA5;\n"
"    border-color: #185FA5;\n"
"}\n"
"QRadioButton::indicator:hover { border-color: #185FA5; }\n"
"\n"
"/* === STATUS BAR === */\n"
"QStatusBar {\n"
"    background: #F4F4F0;\n"
"    color: #72716D;\n"
"    font-size: 9pt;\n"
"    border-top: 1px solid #E2E2DC;\n"
"}\n"
"QStatusBar QLabel {\n"
"    color: #72716D;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"/* === SCROLLBARS === */\n"
"QScrollBar:vertical {\n"
"    background: #F4F4F0;\n"
"    width: 8px;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #CBCAC5;\n"
"    border-radius: 4px;\n"
"    min-height: 24px;\n"
"}\n"
"QScrollBar::handle:vertical:hover { background: #185FA5; }\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0; }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical { background: transparent; }\n"
"QScrollBar:horizontal {\n"
"    background: #F4F4F0;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"    margin: 0;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #CBCAC5;\n"
"    border-radius: 4px;\n"
"    min-width: 24px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover { background: #185FA5; }\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal { width: 0; }\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal { background: transparent; }\n"
"\n"
"/* === TOOLTIP === */\n"
"QToolTip {\n"
"    background: #1A1A18;\n"
"    color: #F9F9F9;\n"
"    border: none;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"    font-size: 9pt;\n"
"}\n"
"    ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 701, 661))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.MainTab = QtWidgets.QWidget()
        self.MainTab.setObjectName("MainTab")
        self.stop_Button = QtWidgets.QPushButton(parent=self.MainTab)
        self.stop_Button.setGeometry(QtCore.QRect(170, 130, 61, 61))
        self.stop_Button.setObjectName("stop_Button")
        self.run_Button = QtWidgets.QPushButton(parent=self.MainTab)
        self.run_Button.setGeometry(QtCore.QRect(80, 130, 61, 61))
        self.run_Button.setObjectName("run_Button")
        self.Recipe_comboBox = QtWidgets.QComboBox(parent=self.MainTab)
        self.Recipe_comboBox.setGeometry(QtCore.QRect(70, 50, 221, 22))
        self.Recipe_comboBox.setObjectName("Recipe_comboBox")
        self.Recipe_comboBox.addItem("")
        self.RobotStatus_Table = QtWidgets.QTableWidget(parent=self.MainTab)
        self.RobotStatus_Table.setGeometry(QtCore.QRect(70, 210, 561, 281))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RobotStatus_Table.setFont(font)
        self.RobotStatus_Table.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RobotStatus_Table.setObjectName("RobotStatus_Table")
        self.RobotStatus_Table.setColumnCount(2)
        self.RobotStatus_Table.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RobotStatus_Table.setHorizontalHeaderItem(1, item)
        self.RobotStatus_Table.horizontalHeader().setDefaultSectionSize(250)
        self.RobotStatus_Table.verticalHeader().setDefaultSectionSize(22)
        self.RobotStatus_Table.verticalHeader().setMinimumSectionSize(22)
        self.label_18 = QtWidgets.QLabel(parent=self.MainTab)
        self.label_18.setGeometry(QtCore.QRect(70, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(parent=self.MainTab)
        self.label_17.setGeometry(QtCore.QRect(520, 30, 101, 16))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.runSpeed_spinBox = QtWidgets.QSpinBox(parent=self.MainTab)
        self.runSpeed_spinBox.setGeometry(QtCore.QRect(520, 50, 101, 22))
        self.runSpeed_spinBox.setMaximum(100)
        self.runSpeed_spinBox.setProperty("value", 25)
        self.runSpeed_spinBox.setObjectName("runSpeed_spinBox")
        self.tabWidget.addTab(self.MainTab, "")
        self.JoggingTab = QtWidgets.QWidget()
        self.JoggingTab.setObjectName("JoggingTab")
        self.label = QtWidgets.QLabel(parent=self.JoggingTab)
        self.label.setGeometry(QtCore.QRect(30, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_JogMode = QtWidgets.QComboBox(parent=self.JoggingTab)
        self.comboBox_JogMode.setGeometry(QtCore.QRect(120, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_JogMode.setFont(font)
        self.comboBox_JogMode.setObjectName("comboBox_JogMode")
        self.comboBox_JogMode.addItem("")
        self.comboBox_JogMode.addItem("")
        self.coordJog = QtWidgets.QWidget(parent=self.JoggingTab)
        self.coordJog.setGeometry(QtCore.QRect(30, 60, 411, 261))
        self.coordJog.setToolTipDuration(-3)
        self.coordJog.setAutoFillBackground(True)
        self.coordJog.setObjectName("coordJog")
        self.Y_jog_minus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Y_jog_minus_Button.setGeometry(QtCore.QRect(50, 180, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Y_jog_minus_Button.setFont(font)
        self.Y_jog_minus_Button.setAutoRepeat(False)
        self.Y_jog_minus_Button.setAutoRepeatDelay(100)
        self.Y_jog_minus_Button.setAutoRepeatInterval(10)
        self.Y_jog_minus_Button.setObjectName("Y_jog_minus_Button")
        self.Y_jog_plus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Y_jog_plus_Button.setGeometry(QtCore.QRect(50, 20, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Y_jog_plus_Button.setFont(font)
        self.Y_jog_plus_Button.setAutoRepeat(False)
        self.Y_jog_plus_Button.setAutoRepeatDelay(100)
        self.Y_jog_plus_Button.setAutoRepeatInterval(10)
        self.Y_jog_plus_Button.setObjectName("Y_jog_plus_Button")
        self.X_jog_plus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.X_jog_plus_Button.setGeometry(QtCore.QRect(90, 100, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.X_jog_plus_Button.setFont(font)
        self.X_jog_plus_Button.setAutoRepeat(False)
        self.X_jog_plus_Button.setAutoRepeatDelay(100)
        self.X_jog_plus_Button.setAutoRepeatInterval(10)
        self.X_jog_plus_Button.setObjectName("X_jog_plus_Button")
        self.X_jog_minus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.X_jog_minus_Button.setGeometry(QtCore.QRect(10, 100, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.X_jog_minus_Button.setFont(font)
        self.X_jog_minus_Button.setAutoRepeat(False)
        self.X_jog_minus_Button.setAutoRepeatDelay(100)
        self.X_jog_minus_Button.setAutoRepeatInterval(10)
        self.X_jog_minus_Button.setObjectName("X_jog_minus_Button")
        self.Z_jog_minus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Z_jog_minus_Button.setGeometry(QtCore.QRect(160, 140, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Z_jog_minus_Button.setFont(font)
        self.Z_jog_minus_Button.setAutoRepeat(False)
        self.Z_jog_minus_Button.setAutoRepeatDelay(100)
        self.Z_jog_minus_Button.setAutoRepeatInterval(10)
        self.Z_jog_minus_Button.setObjectName("Z_jog_minus_Button")
        self.Z_jog_plus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Z_jog_plus_Button.setGeometry(QtCore.QRect(160, 50, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Z_jog_plus_Button.setFont(font)
        self.Z_jog_plus_Button.setAutoRepeat(False)
        self.Z_jog_plus_Button.setAutoRepeatDelay(100)
        self.Z_jog_plus_Button.setAutoRepeatInterval(10)
        self.Z_jog_plus_Button.setObjectName("Z_jog_plus_Button")
        self.Rx_jog_minus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Rx_jog_minus_Button.setGeometry(QtCore.QRect(250, 20, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Rx_jog_minus_Button.setFont(font)
        self.Rx_jog_minus_Button.setAutoRepeat(False)
        self.Rx_jog_minus_Button.setAutoRepeatDelay(100)
        self.Rx_jog_minus_Button.setAutoRepeatInterval(10)
        self.Rx_jog_minus_Button.setObjectName("Rx_jog_minus_Button")
        self.Rx_jog_plus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Rx_jog_plus_Button.setGeometry(QtCore.QRect(330, 20, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Rx_jog_plus_Button.setFont(font)
        self.Rx_jog_plus_Button.setAutoRepeat(False)
        self.Rx_jog_plus_Button.setAutoRepeatDelay(100)
        self.Rx_jog_plus_Button.setAutoRepeatInterval(10)
        self.Rx_jog_plus_Button.setObjectName("Rx_jog_plus_Button")
        self.Ry_jog_minus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Ry_jog_minus_Button.setGeometry(QtCore.QRect(250, 100, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Ry_jog_minus_Button.setFont(font)
        self.Ry_jog_minus_Button.setAutoRepeat(False)
        self.Ry_jog_minus_Button.setAutoRepeatDelay(100)
        self.Ry_jog_minus_Button.setAutoRepeatInterval(10)
        self.Ry_jog_minus_Button.setObjectName("Ry_jog_minus_Button")
        self.Ry_jog_plus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Ry_jog_plus_Button.setGeometry(QtCore.QRect(330, 100, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Ry_jog_plus_Button.setFont(font)
        self.Ry_jog_plus_Button.setAutoRepeat(False)
        self.Ry_jog_plus_Button.setAutoRepeatDelay(100)
        self.Ry_jog_plus_Button.setAutoRepeatInterval(10)
        self.Ry_jog_plus_Button.setObjectName("Ry_jog_plus_Button")
        self.Rz_jog_minus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Rz_jog_minus_Button.setGeometry(QtCore.QRect(250, 180, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Rz_jog_minus_Button.setFont(font)
        self.Rz_jog_minus_Button.setAutoRepeat(False)
        self.Rz_jog_minus_Button.setAutoRepeatDelay(100)
        self.Rz_jog_minus_Button.setAutoRepeatInterval(10)
        self.Rz_jog_minus_Button.setObjectName("Rz_jog_minus_Button")
        self.Rz_jog_plus_Button = QtWidgets.QPushButton(parent=self.coordJog)
        self.Rz_jog_plus_Button.setGeometry(QtCore.QRect(330, 180, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Rz_jog_plus_Button.setFont(font)
        self.Rz_jog_plus_Button.setAutoRepeat(False)
        self.Rz_jog_plus_Button.setAutoRepeatDelay(100)
        self.Rz_jog_plus_Button.setAutoRepeatInterval(10)
        self.Rz_jog_plus_Button.setObjectName("Rz_jog_plus_Button")
        self.comboBox_RobotSelect = QtWidgets.QComboBox(parent=self.JoggingTab)
        self.comboBox_RobotSelect.setGeometry(QtCore.QRect(350, 30, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_RobotSelect.setFont(font)
        self.comboBox_RobotSelect.setObjectName("comboBox_RobotSelect")
        self.comboBox_RobotSelect.addItem("")
        self.label_13 = QtWidgets.QLabel(parent=self.JoggingTab)
        self.label_13.setGeometry(QtCore.QRect(230, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.CoordsTable_Frame = QtWidgets.QFrame(parent=self.JoggingTab)
        self.CoordsTable_Frame.setGeometry(QtCore.QRect(40, 360, 621, 121))
        self.CoordsTable_Frame.setAutoFillBackground(True)
        self.CoordsTable_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CoordsTable_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CoordsTable_Frame.setObjectName("CoordsTable_Frame")
        self.coordsTable = QtWidgets.QTableWidget(parent=self.CoordsTable_Frame)
        self.coordsTable.setEnabled(True)
        self.coordsTable.setGeometry(QtCore.QRect(50, 30, 521, 71))
        self.coordsTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.coordsTable.setObjectName("coordsTable")
        self.coordsTable.setColumnCount(6)
        self.coordsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordsTable.setItem(0, 5, item)
        self.coordsTable.horizontalHeader().setDefaultSectionSize(70)
        self.label_4 = QtWidgets.QLabel(parent=self.CoordsTable_Frame)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.statusLabel = QtWidgets.QLabel(parent=self.JoggingTab)
        self.statusLabel.setGeometry(QtCore.QRect(100, 330, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.label_15 = QtWidgets.QLabel(parent=self.JoggingTab)
        self.label_15.setGeometry(QtCore.QRect(40, 330, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.jointJog = QtWidgets.QWidget(parent=self.JoggingTab)
        self.jointJog.setGeometry(QtCore.QRect(30, 60, 411, 261))
        self.jointJog.setToolTipDuration(-3)
        self.jointJog.setAutoFillBackground(True)
        self.jointJog.setObjectName("jointJog")
        self.J1_jog_minus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J1_jog_minus_Button.setGeometry(QtCore.QRect(30, 20, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J1_jog_minus_Button.setFont(font)
        self.J1_jog_minus_Button.setAutoRepeat(False)
        self.J1_jog_minus_Button.setAutoRepeatDelay(100)
        self.J1_jog_minus_Button.setAutoRepeatInterval(20)
        self.J1_jog_minus_Button.setObjectName("J1_jog_minus_Button")
        self.J1_jog_plus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J1_jog_plus_Button.setGeometry(QtCore.QRect(110, 20, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J1_jog_plus_Button.setFont(font)
        self.J1_jog_plus_Button.setAutoRepeat(False)
        self.J1_jog_plus_Button.setAutoRepeatDelay(100)
        self.J1_jog_plus_Button.setAutoRepeatInterval(20)
        self.J1_jog_plus_Button.setObjectName("J1_jog_plus_Button")
        self.J2_jog_plus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J2_jog_plus_Button.setGeometry(QtCore.QRect(110, 100, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J2_jog_plus_Button.setFont(font)
        self.J2_jog_plus_Button.setAutoRepeat(False)
        self.J2_jog_plus_Button.setAutoRepeatDelay(100)
        self.J2_jog_plus_Button.setAutoRepeatInterval(10)
        self.J2_jog_plus_Button.setObjectName("J2_jog_plus_Button")
        self.J2_jog_minus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J2_jog_minus_Button.setGeometry(QtCore.QRect(30, 100, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J2_jog_minus_Button.setFont(font)
        self.J2_jog_minus_Button.setAutoRepeat(False)
        self.J2_jog_minus_Button.setAutoRepeatDelay(100)
        self.J2_jog_minus_Button.setAutoRepeatInterval(10)
        self.J2_jog_minus_Button.setObjectName("J2_jog_minus_Button")
        self.J3_jog_minus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J3_jog_minus_Button.setGeometry(QtCore.QRect(30, 180, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J3_jog_minus_Button.setFont(font)
        self.J3_jog_minus_Button.setAutoRepeat(False)
        self.J3_jog_minus_Button.setAutoRepeatDelay(100)
        self.J3_jog_minus_Button.setAutoRepeatInterval(10)
        self.J3_jog_minus_Button.setObjectName("J3_jog_minus_Button")
        self.J3_jog_plus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J3_jog_plus_Button.setGeometry(QtCore.QRect(110, 180, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J3_jog_plus_Button.setFont(font)
        self.J3_jog_plus_Button.setAutoRepeat(False)
        self.J3_jog_plus_Button.setAutoRepeatDelay(100)
        self.J3_jog_plus_Button.setAutoRepeatInterval(10)
        self.J3_jog_plus_Button.setObjectName("J3_jog_plus_Button")
        self.J4_jog_minus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J4_jog_minus_Button.setGeometry(QtCore.QRect(240, 20, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J4_jog_minus_Button.setFont(font)
        self.J4_jog_minus_Button.setAutoRepeat(False)
        self.J4_jog_minus_Button.setAutoRepeatDelay(100)
        self.J4_jog_minus_Button.setAutoRepeatInterval(10)
        self.J4_jog_minus_Button.setObjectName("J4_jog_minus_Button")
        self.J4_jog_plus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J4_jog_plus_Button.setGeometry(QtCore.QRect(320, 20, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J4_jog_plus_Button.setFont(font)
        self.J4_jog_plus_Button.setAutoRepeat(False)
        self.J4_jog_plus_Button.setAutoRepeatDelay(100)
        self.J4_jog_plus_Button.setAutoRepeatInterval(10)
        self.J4_jog_plus_Button.setObjectName("J4_jog_plus_Button")
        self.J5_jog_minus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J5_jog_minus_Button.setGeometry(QtCore.QRect(240, 100, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J5_jog_minus_Button.setFont(font)
        self.J5_jog_minus_Button.setAutoRepeat(False)
        self.J5_jog_minus_Button.setAutoRepeatDelay(100)
        self.J5_jog_minus_Button.setAutoRepeatInterval(10)
        self.J5_jog_minus_Button.setObjectName("J5_jog_minus_Button")
        self.J5_jog_plus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J5_jog_plus_Button.setGeometry(QtCore.QRect(320, 100, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J5_jog_plus_Button.setFont(font)
        self.J5_jog_plus_Button.setAutoRepeat(False)
        self.J5_jog_plus_Button.setAutoRepeatDelay(100)
        self.J5_jog_plus_Button.setAutoRepeatInterval(10)
        self.J5_jog_plus_Button.setObjectName("J5_jog_plus_Button")
        self.J6_jog_minus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J6_jog_minus_Button.setGeometry(QtCore.QRect(240, 180, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J6_jog_minus_Button.setFont(font)
        self.J6_jog_minus_Button.setAutoRepeat(False)
        self.J6_jog_minus_Button.setAutoRepeatDelay(100)
        self.J6_jog_minus_Button.setAutoRepeatInterval(10)
        self.J6_jog_minus_Button.setObjectName("J6_jog_minus_Button")
        self.J6_jog_plus_Button = QtWidgets.QPushButton(parent=self.jointJog)
        self.J6_jog_plus_Button.setGeometry(QtCore.QRect(320, 180, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.J6_jog_plus_Button.setFont(font)
        self.J6_jog_plus_Button.setAutoRepeat(False)
        self.J6_jog_plus_Button.setAutoRepeatDelay(100)
        self.J6_jog_plus_Button.setAutoRepeatInterval(10)
        self.J6_jog_plus_Button.setObjectName("J6_jog_plus_Button")
        self.Speed_Frame = QtWidgets.QFrame(parent=self.JoggingTab)
        self.Speed_Frame.setGeometry(QtCore.QRect(470, 60, 181, 261))
        self.Speed_Frame.setAutoFillBackground(True)
        self.Speed_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Speed_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Speed_Frame.setObjectName("Speed_Frame")
        self.SpeedLable = QtWidgets.QLabel(parent=self.Speed_Frame)
        self.SpeedLable.setGeometry(QtCore.QRect(130, 190, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpeedLable.setFont(font)
        self.SpeedLable.setObjectName("SpeedLable")
        self.radioButtonContinuous = QtWidgets.QRadioButton(parent=self.Speed_Frame)
        self.radioButtonContinuous.setGeometry(QtCore.QRect(10, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonContinuous.setFont(font)
        self.radioButtonContinuous.setObjectName("radioButtonContinuous")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButtonContinuous)
        self.spinBoxStep = QtWidgets.QSpinBox(parent=self.Speed_Frame)
        self.spinBoxStep.setGeometry(QtCore.QRect(100, 10, 71, 20))
        self.spinBoxStep.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxStep.setFont(font)
        self.spinBoxStep.setMinimum(1)
        self.spinBoxStep.setMaximum(20)
        self.spinBoxStep.setObjectName("spinBoxStep")
        self.label_3 = QtWidgets.QLabel(parent=self.Speed_Frame)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.speedSlider = QtWidgets.QSlider(parent=self.Speed_Frame)
        self.speedSlider.setGeometry(QtCore.QRect(10, 220, 161, 21))
        self.speedSlider.setMinimum(1)
        self.speedSlider.setMaximum(100)
        self.speedSlider.setProperty("value", 1)
        self.speedSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.ReleaseServos_Button = QtWidgets.QPushButton(parent=self.Speed_Frame)
        self.ReleaseServos_Button.setGeometry(QtCore.QRect(30, 90, 120, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ReleaseServos_Button.setFont(font)
        self.ReleaseServos_Button.setObjectName("ReleaseServos_Button")
        self.radioButtonStep = QtWidgets.QRadioButton(parent=self.Speed_Frame)
        self.radioButtonStep.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.radioButtonStep.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonStep.setFont(font)
        self.radioButtonStep.setIconSize(QtCore.QSize(12, 12))
        self.radioButtonStep.setChecked(True)
        self.radioButtonStep.setObjectName("radioButtonStep")
        self.buttonGroup_2.addButton(self.radioButtonStep)
        self.LockServos_Button = QtWidgets.QPushButton(parent=self.Speed_Frame)
        self.LockServos_Button.setGeometry(QtCore.QRect(30, 90, 120, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LockServos_Button.setFont(font)
        self.LockServos_Button.setObjectName("LockServos_Button")
        self.LockServos_Button.raise_()
        self.SpeedLable.raise_()
        self.radioButtonContinuous.raise_()
        self.spinBoxStep.raise_()
        self.label_3.raise_()
        self.speedSlider.raise_()
        self.ReleaseServos_Button.raise_()
        self.radioButtonStep.raise_()
        self.Teach_Frame = QtWidgets.QFrame(parent=self.JoggingTab)
        self.Teach_Frame.setGeometry(QtCore.QRect(40, 500, 621, 91))
        self.Teach_Frame.setAutoFillBackground(True)
        self.Teach_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Teach_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Teach_Frame.setObjectName("Teach_Frame")
        self.GoToPoint_Button = QtWidgets.QPushButton(parent=self.Teach_Frame)
        self.GoToPoint_Button.setGeometry(QtCore.QRect(520, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GoToPoint_Button.setFont(font)
        self.GoToPoint_Button.setObjectName("GoToPoint_Button")
        self.label_14 = QtWidgets.QLabel(parent=self.Teach_Frame)
        self.label_14.setGeometry(QtCore.QRect(240, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.PointsComboBox = QtWidgets.QComboBox(parent=self.Teach_Frame)
        self.PointsComboBox.setGeometry(QtCore.QRect(240, 30, 151, 21))
        self.PointsComboBox.setObjectName("PointsComboBox")
        self.PointsComboBox.addItem("")
        self.TeachPoint = QtWidgets.QPushButton(parent=self.Teach_Frame)
        self.TeachPoint.setGeometry(QtCore.QRect(440, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TeachPoint.setFont(font)
        self.TeachPoint.setObjectName("TeachPoint")
        self.PointSavedLabel = QtWidgets.QLabel(parent=self.Teach_Frame)
        self.PointSavedLabel.setGeometry(QtCore.QRect(60, 60, 501, 20))
        self.PointSavedLabel.setText("")
        self.PointSavedLabel.setObjectName("PointSavedLabel")
        self.RecipeTeach_comboBox = QtWidgets.QComboBox(parent=self.Teach_Frame)
        self.RecipeTeach_comboBox.setGeometry(QtCore.QRect(20, 30, 151, 22))
        self.RecipeTeach_comboBox.setObjectName("RecipeTeach_comboBox")
        self.RecipeTeach_comboBox.addItem("")
        self.label_19 = QtWidgets.QLabel(parent=self.Teach_Frame)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.AngleTable_Frame = QtWidgets.QFrame(parent=self.JoggingTab)
        self.AngleTable_Frame.setGeometry(QtCore.QRect(40, 360, 621, 121))
        self.AngleTable_Frame.setAutoFillBackground(True)
        self.AngleTable_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.AngleTable_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.AngleTable_Frame.setObjectName("AngleTable_Frame")
        self.anglesTable = QtWidgets.QTableWidget(parent=self.AngleTable_Frame)
        self.anglesTable.setGeometry(QtCore.QRect(50, 30, 521, 71))
        self.anglesTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.anglesTable.setObjectName("anglesTable")
        self.anglesTable.setColumnCount(6)
        self.anglesTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.anglesTable.setItem(0, 5, item)
        self.anglesTable.horizontalHeader().setDefaultSectionSize(70)
        self.label_2 = QtWidgets.QLabel(parent=self.AngleTable_Frame)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.CoordsTable_Frame.raise_()
        self.coordJog.raise_()
        self.label.raise_()
        self.comboBox_JogMode.raise_()
        self.comboBox_RobotSelect.raise_()
        self.label_13.raise_()
        self.statusLabel.raise_()
        self.label_15.raise_()
        self.jointJog.raise_()
        self.Speed_Frame.raise_()
        self.Teach_Frame.raise_()
        self.AngleTable_Frame.raise_()
        self.tabWidget.addTab(self.JoggingTab, "")
        self.ConfigTab = QtWidgets.QWidget()
        self.ConfigTab.setObjectName("ConfigTab")
        self.groupBox = QtWidgets.QGroupBox(parent=self.ConfigTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 671, 321))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.DeleteRecipe_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.DeleteRecipe_Button.setGeometry(QtCore.QRect(70, 280, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DeleteRecipe_Button.setFont(font)
        self.DeleteRecipe_Button.setObjectName("DeleteRecipe_Button")
        self.AddRecipe_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.AddRecipe_Button.setGeometry(QtCore.QRect(10, 280, 41, 31))
        self.AddRecipe_Button.setObjectName("AddRecipe_Button")
        self.RobotPoints_Table = QtWidgets.QTabWidget(parent=self.groupBox)
        self.RobotPoints_Table.setGeometry(QtCore.QRect(120, 20, 471, 291))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RobotPoints_Table.setFont(font)
        self.RobotPoints_Table.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.RobotPoints_Table.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.RobotPoints_Table.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.RobotPoints_Table.setObjectName("RobotPoints_Table")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Robot1_PointsTable = QtWidgets.QTableWidget(parent=self.tab)
        self.Robot1_PointsTable.setGeometry(QtCore.QRect(10, 7, 441, 251))
        self.Robot1_PointsTable.setLineWidth(3)
        self.Robot1_PointsTable.setMidLineWidth(0)
        self.Robot1_PointsTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AllEditTriggers)
        self.Robot1_PointsTable.setObjectName("Robot1_PointsTable")
        self.Robot1_PointsTable.setColumnCount(7)
        self.Robot1_PointsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Robot1_PointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot1_PointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot1_PointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot1_PointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot1_PointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot1_PointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot1_PointsTable.setHorizontalHeaderItem(6, item)
        self.Robot1_PointsTable.horizontalHeader().setDefaultSectionSize(62)
        self.RobotPoints_Table.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Robot2_PointsTable = QtWidgets.QTableWidget(parent=self.tab_2)
        self.Robot2_PointsTable.setGeometry(QtCore.QRect(7, 7, 451, 251))
        self.Robot2_PointsTable.setLineWidth(3)
        self.Robot2_PointsTable.setMidLineWidth(0)
        self.Robot2_PointsTable.setObjectName("Robot2_PointsTable")
        self.Robot2_PointsTable.setColumnCount(7)
        self.Robot2_PointsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Robot2_PointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot2_PointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot2_PointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot2_PointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot2_PointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot2_PointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot2_PointsTable.setHorizontalHeaderItem(6, item)
        self.Robot2_PointsTable.horizontalHeader().setDefaultSectionSize(62)
        self.RobotPoints_Table.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Robot3_PointsTable = QtWidgets.QTableWidget(parent=self.tab_3)
        self.Robot3_PointsTable.setGeometry(QtCore.QRect(7, 7, 451, 251))
        self.Robot3_PointsTable.setLineWidth(3)
        self.Robot3_PointsTable.setMidLineWidth(0)
        self.Robot3_PointsTable.setObjectName("Robot3_PointsTable")
        self.Robot3_PointsTable.setColumnCount(7)
        self.Robot3_PointsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Robot3_PointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot3_PointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot3_PointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot3_PointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot3_PointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot3_PointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot3_PointsTable.setHorizontalHeaderItem(6, item)
        self.Robot3_PointsTable.horizontalHeader().setDefaultSectionSize(62)
        self.RobotPoints_Table.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Robot4_PointsTable = QtWidgets.QTableWidget(parent=self.tab_4)
        self.Robot4_PointsTable.setGeometry(QtCore.QRect(7, 7, 451, 251))
        self.Robot4_PointsTable.setLineWidth(3)
        self.Robot4_PointsTable.setMidLineWidth(0)
        self.Robot4_PointsTable.setObjectName("Robot4_PointsTable")
        self.Robot4_PointsTable.setColumnCount(7)
        self.Robot4_PointsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Robot4_PointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot4_PointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot4_PointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot4_PointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot4_PointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot4_PointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot4_PointsTable.setHorizontalHeaderItem(6, item)
        self.Robot4_PointsTable.horizontalHeader().setDefaultSectionSize(62)
        self.RobotPoints_Table.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Robot5_PointsTable = QtWidgets.QTableWidget(parent=self.tab_5)
        self.Robot5_PointsTable.setGeometry(QtCore.QRect(7, 7, 451, 251))
        self.Robot5_PointsTable.setLineWidth(3)
        self.Robot5_PointsTable.setMidLineWidth(0)
        self.Robot5_PointsTable.setObjectName("Robot5_PointsTable")
        self.Robot5_PointsTable.setColumnCount(7)
        self.Robot5_PointsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Robot5_PointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot5_PointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot5_PointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot5_PointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot5_PointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot5_PointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot5_PointsTable.setHorizontalHeaderItem(6, item)
        self.Robot5_PointsTable.horizontalHeader().setDefaultSectionSize(62)
        self.RobotPoints_Table.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.Robot6_PointsTable = QtWidgets.QTableWidget(parent=self.tab_6)
        self.Robot6_PointsTable.setGeometry(QtCore.QRect(7, 7, 451, 251))
        self.Robot6_PointsTable.setLineWidth(3)
        self.Robot6_PointsTable.setMidLineWidth(0)
        self.Robot6_PointsTable.setObjectName("Robot6_PointsTable")
        self.Robot6_PointsTable.setColumnCount(7)
        self.Robot6_PointsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Robot6_PointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot6_PointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot6_PointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot6_PointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot6_PointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot6_PointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot6_PointsTable.setHorizontalHeaderItem(6, item)
        self.Robot6_PointsTable.horizontalHeader().setDefaultSectionSize(62)
        self.RobotPoints_Table.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.Robot7_PointsTable = QtWidgets.QTableWidget(parent=self.tab_7)
        self.Robot7_PointsTable.setGeometry(QtCore.QRect(7, 7, 451, 251))
        self.Robot7_PointsTable.setLineWidth(3)
        self.Robot7_PointsTable.setMidLineWidth(0)
        self.Robot7_PointsTable.setObjectName("Robot7_PointsTable")
        self.Robot7_PointsTable.setColumnCount(7)
        self.Robot7_PointsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Robot7_PointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot7_PointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot7_PointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot7_PointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot7_PointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot7_PointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot7_PointsTable.setHorizontalHeaderItem(6, item)
        self.Robot7_PointsTable.horizontalHeader().setDefaultSectionSize(62)
        self.RobotPoints_Table.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.Robot8_PointsTable = QtWidgets.QTableWidget(parent=self.tab_8)
        self.Robot8_PointsTable.setGeometry(QtCore.QRect(7, 7, 451, 251))
        self.Robot8_PointsTable.setLineWidth(3)
        self.Robot8_PointsTable.setMidLineWidth(0)
        self.Robot8_PointsTable.setObjectName("Robot8_PointsTable")
        self.Robot8_PointsTable.setColumnCount(7)
        self.Robot8_PointsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Robot8_PointsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot8_PointsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot8_PointsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot8_PointsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot8_PointsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot8_PointsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Robot8_PointsTable.setHorizontalHeaderItem(6, item)
        self.Robot8_PointsTable.horizontalHeader().setDefaultSectionSize(62)
        self.RobotPoints_Table.addTab(self.tab_8, "")
        self.Recipe_List = QtWidgets.QListWidget(parent=self.groupBox)
        self.Recipe_List.setGeometry(QtCore.QRect(10, 40, 101, 231))
        self.Recipe_List.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.CurrentChanged|QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.Recipe_List.setObjectName("Recipe_List")
        self.DeletePoint_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.DeletePoint_Button.setGeometry(QtCore.QRect(600, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.DeletePoint_Button.setFont(font)
        self.DeletePoint_Button.setObjectName("DeletePoint_Button")
        self.AddPoint_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.AddPoint_Button.setGeometry(QtCore.QRect(600, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.AddPoint_Button.setFont(font)
        self.AddPoint_Button.setObjectName("AddPoint_Button")
        self.SavePoints_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.SavePoints_Button.setGeometry(QtCore.QRect(600, 280, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SavePoints_Button.setFont(font)
        self.SavePoints_Button.setObjectName("SavePoints_Button")
        self.MoveUp_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.MoveUp_Button.setGeometry(QtCore.QRect(610, 160, 41, 31))
        self.MoveUp_Button.setObjectName("MoveUp_Button")
        self.MoveDown_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.MoveDown_Button.setGeometry(QtCore.QRect(610, 200, 41, 31))
        self.MoveDown_Button.setObjectName("MoveDown_Button")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_16.setObjectName("label_16")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.ConfigTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 340, 441, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(parent=self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 421, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.Robot_1_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.Robot_1_ip.setFont(font)
        self.Robot_1_ip.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.Robot_1_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Robot_1_ip.setObjectName("Robot_1_ip")
        self.gridLayout.addWidget(self.Robot_1_ip, 0, 1, 1, 1)
        self.TestConnection_1_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TestConnection_1_Button.setFont(font)
        self.TestConnection_1_Button.setObjectName("TestConnection_1_Button")
        self.gridLayout.addWidget(self.TestConnection_1_Button, 0, 2, 1, 1)
        self.TestConnection_1_Status = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TestConnection_1_Status.setFont(font)
        self.TestConnection_1_Status.setAutoFillBackground(False)
        self.TestConnection_1_Status.setObjectName("TestConnection_1_Status")
        self.gridLayout.addWidget(self.TestConnection_1_Status, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.Robot_2_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Robot_2_ip.setFont(font)
        self.Robot_2_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Robot_2_ip.setObjectName("Robot_2_ip")
        self.gridLayout.addWidget(self.Robot_2_ip, 1, 1, 1, 1)
        self.TestConnection_2_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TestConnection_2_Button.setFont(font)
        self.TestConnection_2_Button.setObjectName("TestConnection_2_Button")
        self.gridLayout.addWidget(self.TestConnection_2_Button, 1, 2, 1, 1)
        self.TestConnection_2_Status = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TestConnection_2_Status.setFont(font)
        self.TestConnection_2_Status.setObjectName("TestConnection_2_Status")
        self.gridLayout.addWidget(self.TestConnection_2_Status, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.Robot_3_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Robot_3_ip.setFont(font)
        self.Robot_3_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Robot_3_ip.setObjectName("Robot_3_ip")
        self.gridLayout.addWidget(self.Robot_3_ip, 2, 1, 1, 1)
        self.TestConnection_3_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TestConnection_3_Button.setFont(font)
        self.TestConnection_3_Button.setObjectName("TestConnection_3_Button")
        self.gridLayout.addWidget(self.TestConnection_3_Button, 2, 2, 1, 1)
        self.TestConnection_3_Status = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TestConnection_3_Status.setFont(font)
        self.TestConnection_3_Status.setObjectName("TestConnection_3_Status")
        self.gridLayout.addWidget(self.TestConnection_3_Status, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.Robot_4_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Robot_4_ip.setFont(font)
        self.Robot_4_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Robot_4_ip.setObjectName("Robot_4_ip")
        self.gridLayout.addWidget(self.Robot_4_ip, 3, 1, 1, 1)
        self.TestConnection_4_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TestConnection_4_Button.setFont(font)
        self.TestConnection_4_Button.setObjectName("TestConnection_4_Button")
        self.gridLayout.addWidget(self.TestConnection_4_Button, 3, 2, 1, 1)
        self.TestConnection_4_Status = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TestConnection_4_Status.setFont(font)
        self.TestConnection_4_Status.setObjectName("TestConnection_4_Status")
        self.gridLayout.addWidget(self.TestConnection_4_Status, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.Robot_5_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Robot_5_ip.setFont(font)
        self.Robot_5_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Robot_5_ip.setObjectName("Robot_5_ip")
        self.gridLayout.addWidget(self.Robot_5_ip, 4, 1, 1, 1)
        self.TestConnection_5_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TestConnection_5_Button.setFont(font)
        self.TestConnection_5_Button.setObjectName("TestConnection_5_Button")
        self.gridLayout.addWidget(self.TestConnection_5_Button, 4, 2, 1, 1)
        self.TestConnection_5_Status = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TestConnection_5_Status.setFont(font)
        self.TestConnection_5_Status.setObjectName("TestConnection_5_Status")
        self.gridLayout.addWidget(self.TestConnection_5_Status, 4, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.Robot_6_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Robot_6_ip.setFont(font)
        self.Robot_6_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Robot_6_ip.setObjectName("Robot_6_ip")
        self.gridLayout.addWidget(self.Robot_6_ip, 5, 1, 1, 1)
        self.TestConnection_6_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TestConnection_6_Button.setFont(font)
        self.TestConnection_6_Button.setObjectName("TestConnection_6_Button")
        self.gridLayout.addWidget(self.TestConnection_6_Button, 5, 2, 1, 1)
        self.TestConnection_6_Status = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TestConnection_6_Status.setFont(font)
        self.TestConnection_6_Status.setObjectName("TestConnection_6_Status")
        self.gridLayout.addWidget(self.TestConnection_6_Status, 5, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.Robot_7_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Robot_7_ip.setFont(font)
        self.Robot_7_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Robot_7_ip.setObjectName("Robot_7_ip")
        self.gridLayout.addWidget(self.Robot_7_ip, 6, 1, 1, 1)
        self.TestConnection_7_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TestConnection_7_Button.setFont(font)
        self.TestConnection_7_Button.setObjectName("TestConnection_7_Button")
        self.gridLayout.addWidget(self.TestConnection_7_Button, 6, 2, 1, 1)
        self.TestConnection_7_Status = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TestConnection_7_Status.setFont(font)
        self.TestConnection_7_Status.setObjectName("TestConnection_7_Status")
        self.gridLayout.addWidget(self.TestConnection_7_Status, 6, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.Robot_8_ip = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Robot_8_ip.setFont(font)
        self.Robot_8_ip.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Robot_8_ip.setObjectName("Robot_8_ip")
        self.gridLayout.addWidget(self.Robot_8_ip, 7, 1, 1, 1)
        self.TestConnection_8_Button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TestConnection_8_Button.setFont(font)
        self.TestConnection_8_Button.setObjectName("TestConnection_8_Button")
        self.gridLayout.addWidget(self.TestConnection_8_Button, 7, 2, 1, 1)
        self.TestConnection_8_Status = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TestConnection_8_Status.setFont(font)
        self.TestConnection_8_Status.setObjectName("TestConnection_8_Status")
        self.gridLayout.addWidget(self.TestConnection_8_Status, 7, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 8)
        self.gridLayout.setColumnStretch(2, 4)
        self.gridLayout.setColumnStretch(3, 3)
        self.SaveConfig_Button = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.SaveConfig_Button.setGeometry(QtCore.QRect(10, 230, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SaveConfig_Button.setFont(font)
        self.SaveConfig_Button.setObjectName("SaveConfig_Button")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.ConfigTab)
        self.groupBox_3.setGeometry(QtCore.QRect(460, 340, 221, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.tabWidget.addTab(self.ConfigTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.RobotPoints_Table.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot Control — Cobot 320"))
        self.stop_Button.setText(_translate("MainWindow", "Stop"))
        self.run_Button.setText(_translate("MainWindow", "Run"))
        self.Recipe_comboBox.setItemText(0, _translate("MainWindow", "None"))
        item = self.RobotStatus_Table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Robot 1"))
        item = self.RobotStatus_Table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Robot 2"))
        item = self.RobotStatus_Table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Robot 3"))
        item = self.RobotStatus_Table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Robot 4"))
        item = self.RobotStatus_Table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Robot 5"))
        item = self.RobotStatus_Table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Robot 6"))
        item = self.RobotStatus_Table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Robot 7"))
        item = self.RobotStatus_Table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Robot 8"))
        item = self.RobotStatus_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Status"))
        item = self.RobotStatus_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Error Information"))
        self.label_18.setText(_translate("MainWindow", "Select Recipe:"))
        self.label_17.setText(_translate("MainWindow", "Robots Speed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainTab), _translate("MainWindow", "Main"))
        self.label.setText(_translate("MainWindow", "Jog Mode:"))
        self.comboBox_JogMode.setItemText(0, _translate("MainWindow", "Joint"))
        self.comboBox_JogMode.setItemText(1, _translate("MainWindow", "Coords"))
        self.Y_jog_minus_Button.setText(_translate("MainWindow", "Y -"))
        self.Y_jog_plus_Button.setText(_translate("MainWindow", "Y +"))
        self.X_jog_plus_Button.setText(_translate("MainWindow", "X +"))
        self.X_jog_minus_Button.setText(_translate("MainWindow", "X -"))
        self.Z_jog_minus_Button.setText(_translate("MainWindow", "Z -"))
        self.Z_jog_plus_Button.setText(_translate("MainWindow", "Z +"))
        self.Rx_jog_minus_Button.setText(_translate("MainWindow", "Rx-"))
        self.Rx_jog_plus_Button.setText(_translate("MainWindow", "Rx+"))
        self.Ry_jog_minus_Button.setText(_translate("MainWindow", "Ry-"))
        self.Ry_jog_plus_Button.setText(_translate("MainWindow", "Ry+"))
        self.Rz_jog_minus_Button.setText(_translate("MainWindow", "Rz-"))
        self.Rz_jog_plus_Button.setText(_translate("MainWindow", "Rz+"))
        self.comboBox_RobotSelect.setItemText(0, _translate("MainWindow", "None"))
        self.label_13.setText(_translate("MainWindow", "Current Robot: "))
        item = self.coordsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Coord"))
        item = self.coordsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.coordsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        item = self.coordsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Z"))
        item = self.coordsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Rx"))
        item = self.coordsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ry"))
        item = self.coordsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Rz"))
        __sortingEnabled = self.coordsTable.isSortingEnabled()
        self.coordsTable.setSortingEnabled(False)
        item = self.coordsTable.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.coordsTable.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.coordsTable.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.coordsTable.item(0, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.coordsTable.item(0, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.coordsTable.item(0, 5)
        item.setText(_translate("MainWindow", "0"))
        self.coordsTable.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Current Coords"))
        self.statusLabel.setText(_translate("MainWindow", "................"))
        self.label_15.setText(_translate("MainWindow", "Status:"))
        self.J1_jog_minus_Button.setText(_translate("MainWindow", "J1 -"))
        self.J1_jog_plus_Button.setText(_translate("MainWindow", "J1 +"))
        self.J2_jog_plus_Button.setText(_translate("MainWindow", "J2 +"))
        self.J2_jog_minus_Button.setText(_translate("MainWindow", "J2 -"))
        self.J3_jog_minus_Button.setText(_translate("MainWindow", "J3 -"))
        self.J3_jog_plus_Button.setText(_translate("MainWindow", "J3 +"))
        self.J4_jog_minus_Button.setText(_translate("MainWindow", "J4 -"))
        self.J4_jog_plus_Button.setText(_translate("MainWindow", "J4 +"))
        self.J5_jog_minus_Button.setText(_translate("MainWindow", "J5 -"))
        self.J5_jog_plus_Button.setText(_translate("MainWindow", "J5 +"))
        self.J6_jog_minus_Button.setText(_translate("MainWindow", "J6 -"))
        self.J6_jog_plus_Button.setText(_translate("MainWindow", "J6 +"))
        self.SpeedLable.setText(_translate("MainWindow", "###"))
        self.radioButtonContinuous.setText(_translate("MainWindow", "Continuous"))
        self.label_3.setText(_translate("MainWindow", "Jog Speed"))
        self.ReleaseServos_Button.setText(_translate("MainWindow", "Release Servos"))
        self.radioButtonStep.setText(_translate("MainWindow", "Step"))
        self.LockServos_Button.setText(_translate("MainWindow", "Focus Servos"))
        self.GoToPoint_Button.setText(_translate("MainWindow", "Go To"))
        self.label_14.setText(_translate("MainWindow", "Point:"))
        self.PointsComboBox.setItemText(0, _translate("MainWindow", "New Point"))
        self.TeachPoint.setText(_translate("MainWindow", "Teach"))
        self.RecipeTeach_comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.label_19.setText(_translate("MainWindow", "Recipe:"))
        item = self.anglesTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Angles"))
        item = self.anglesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Joint 1"))
        item = self.anglesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Joint 2"))
        item = self.anglesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Joint 3"))
        item = self.anglesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Joint 4"))
        item = self.anglesTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Joint 5"))
        item = self.anglesTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Joint 6"))
        __sortingEnabled = self.anglesTable.isSortingEnabled()
        self.anglesTable.setSortingEnabled(False)
        item = self.anglesTable.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.anglesTable.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.anglesTable.item(0, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.anglesTable.item(0, 3)
        item.setText(_translate("MainWindow", "0"))
        item = self.anglesTable.item(0, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.anglesTable.item(0, 5)
        item.setText(_translate("MainWindow", "0"))
        self.anglesTable.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Current Position"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.JoggingTab), _translate("MainWindow", "Jogging"))
        self.groupBox.setTitle(_translate("MainWindow", "Recipe mangement"))
        self.DeleteRecipe_Button.setText(_translate("MainWindow", "Delete"))
        self.AddRecipe_Button.setText(_translate("MainWindow", "New"))
        item = self.Robot1_PointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Point"))
        item = self.Robot1_PointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J1"))
        item = self.Robot1_PointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J2"))
        item = self.Robot1_PointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J3"))
        item = self.Robot1_PointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "J4"))
        item = self.Robot1_PointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "J5"))
        item = self.Robot1_PointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "J6"))
        self.RobotPoints_Table.setTabText(self.RobotPoints_Table.indexOf(self.tab), _translate("MainWindow", "Robot 1"))
        item = self.Robot2_PointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Point"))
        item = self.Robot2_PointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J1"))
        item = self.Robot2_PointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J2"))
        item = self.Robot2_PointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J3"))
        item = self.Robot2_PointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "J4"))
        item = self.Robot2_PointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "J5"))
        item = self.Robot2_PointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "J6"))
        self.RobotPoints_Table.setTabText(self.RobotPoints_Table.indexOf(self.tab_2), _translate("MainWindow", "Robot 2"))
        item = self.Robot3_PointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Point"))
        item = self.Robot3_PointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J1"))
        item = self.Robot3_PointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J2"))
        item = self.Robot3_PointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J3"))
        item = self.Robot3_PointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "J4"))
        item = self.Robot3_PointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "J5"))
        item = self.Robot3_PointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "J6"))
        self.RobotPoints_Table.setTabText(self.RobotPoints_Table.indexOf(self.tab_3), _translate("MainWindow", "Robot 3"))
        item = self.Robot4_PointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Point"))
        item = self.Robot4_PointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J1"))
        item = self.Robot4_PointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J2"))
        item = self.Robot4_PointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J3"))
        item = self.Robot4_PointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "J4"))
        item = self.Robot4_PointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "J5"))
        item = self.Robot4_PointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "J6"))
        self.RobotPoints_Table.setTabText(self.RobotPoints_Table.indexOf(self.tab_4), _translate("MainWindow", "Robot 4"))
        item = self.Robot5_PointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Point"))
        item = self.Robot5_PointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J1"))
        item = self.Robot5_PointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J2"))
        item = self.Robot5_PointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J3"))
        item = self.Robot5_PointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "J4"))
        item = self.Robot5_PointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "J5"))
        item = self.Robot5_PointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "J6"))
        self.RobotPoints_Table.setTabText(self.RobotPoints_Table.indexOf(self.tab_5), _translate("MainWindow", "Robot 5"))
        item = self.Robot6_PointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Point"))
        item = self.Robot6_PointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J1"))
        item = self.Robot6_PointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J2"))
        item = self.Robot6_PointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J3"))
        item = self.Robot6_PointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "J4"))
        item = self.Robot6_PointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "J5"))
        item = self.Robot6_PointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "J6"))
        self.RobotPoints_Table.setTabText(self.RobotPoints_Table.indexOf(self.tab_6), _translate("MainWindow", "Robot 6"))
        item = self.Robot7_PointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Point"))
        item = self.Robot7_PointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J1"))
        item = self.Robot7_PointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J2"))
        item = self.Robot7_PointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J3"))
        item = self.Robot7_PointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "J4"))
        item = self.Robot7_PointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "J5"))
        item = self.Robot7_PointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "J6"))
        self.RobotPoints_Table.setTabText(self.RobotPoints_Table.indexOf(self.tab_7), _translate("MainWindow", "Robot 7"))
        item = self.Robot8_PointsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Point"))
        item = self.Robot8_PointsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J1"))
        item = self.Robot8_PointsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J2"))
        item = self.Robot8_PointsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J3"))
        item = self.Robot8_PointsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "J4"))
        item = self.Robot8_PointsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "J5"))
        item = self.Robot8_PointsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "J6"))
        self.RobotPoints_Table.setTabText(self.RobotPoints_Table.indexOf(self.tab_8), _translate("MainWindow", "Robot 8"))
        self.DeletePoint_Button.setText(_translate("MainWindow", "Delete Point"))
        self.AddPoint_Button.setText(_translate("MainWindow", "Add Point"))
        self.SavePoints_Button.setText(_translate("MainWindow", "Save Points"))
        self.MoveUp_Button.setText(_translate("MainWindow", "Up"))
        self.MoveDown_Button.setText(_translate("MainWindow", "Down"))
        self.label_16.setText(_translate("MainWindow", "Recipes:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "IP Congfiguration"))
        self.label_5.setText(_translate("MainWindow", "Robot 1"))
        self.Robot_1_ip.setInputMask(_translate("MainWindow", " 999 . 999 . 999 . 999 ;_"))
        self.Robot_1_ip.setText(_translate("MainWindow", " 1 .  .  .  "))
        self.TestConnection_1_Button.setText(_translate("MainWindow", "Connect"))
        self.TestConnection_1_Status.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Robot 2"))
        self.Robot_2_ip.setInputMask(_translate("MainWindow", " 999 . 999 . 999 . 999 ;_"))
        self.Robot_2_ip.setText(_translate("MainWindow", " 192 . 162 . 1 . 1 "))
        self.TestConnection_2_Button.setText(_translate("MainWindow", "Connect"))
        self.TestConnection_2_Status.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Robot 3"))
        self.Robot_3_ip.setInputMask(_translate("MainWindow", " 999 . 999 . 999 . 999 ;_"))
        self.Robot_3_ip.setText(_translate("MainWindow", " 192 . 162 . 1 . 1 "))
        self.TestConnection_3_Button.setText(_translate("MainWindow", "Connect"))
        self.TestConnection_3_Status.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Robot 4"))
        self.Robot_4_ip.setInputMask(_translate("MainWindow", " 999 . 999 . 999 . 999 ;_"))
        self.Robot_4_ip.setText(_translate("MainWindow", " 192 . 162 . 1 . 1 "))
        self.TestConnection_4_Button.setText(_translate("MainWindow", "Connect"))
        self.TestConnection_4_Status.setText(_translate("MainWindow", "..."))
        self.label_9.setText(_translate("MainWindow", "Robot 5"))
        self.Robot_5_ip.setInputMask(_translate("MainWindow", " 999 . 999 . 999 . 999 ;_"))
        self.Robot_5_ip.setText(_translate("MainWindow", " 192 . 162 . 1 . 1 "))
        self.TestConnection_5_Button.setText(_translate("MainWindow", "Connect"))
        self.TestConnection_5_Status.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "Robot 6"))
        self.Robot_6_ip.setInputMask(_translate("MainWindow", " 999 . 999 . 999 . 999 ;_"))
        self.Robot_6_ip.setText(_translate("MainWindow", " 192 . 162 . 1 . 1 "))
        self.TestConnection_6_Button.setText(_translate("MainWindow", "Connect"))
        self.TestConnection_6_Status.setText(_translate("MainWindow", "..."))
        self.label_11.setText(_translate("MainWindow", "Robot 7"))
        self.Robot_7_ip.setInputMask(_translate("MainWindow", " 999 . 999 . 999 . 999 ;_"))
        self.Robot_7_ip.setText(_translate("MainWindow", " 192 . 162 . 1 . 1 "))
        self.TestConnection_7_Button.setText(_translate("MainWindow", "Connect"))
        self.TestConnection_7_Status.setText(_translate("MainWindow", "..."))
        self.label_12.setText(_translate("MainWindow", "Robot 8"))
        self.Robot_8_ip.setInputMask(_translate("MainWindow", " 999 . 999 . 999 . 999 ;_"))
        self.Robot_8_ip.setText(_translate("MainWindow", " 192 . 162 . 1 . 1 "))
        self.TestConnection_8_Button.setText(_translate("MainWindow", "Connect"))
        self.TestConnection_8_Status.setText(_translate("MainWindow", "..."))
        self.SaveConfig_Button.setText(_translate("MainWindow", "Save Config"))
        self.groupBox_3.setTitle(_translate("MainWindow", "UPS Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ConfigTab), _translate("MainWindow", "Configuration"))
